import { getAdjacentTiles } from '../../functions/getAdjacentTiles'

test('getAdjacentTiles', () => {
	expect(getAdjacentTiles(1)).toStrictEqual({'R': null, 'T': null, 'B': 5, 'L': 2})
	expect(getAdjacentTiles(2)).toStrictEqual({'R': 1, 'T': null, 'B': 6, 'L': 3})
	expect(getAdjacentTiles(3)).toStrictEqual({'R': 2, 'T': null, 'B': 7, 'L': 4})
	expect(getAdjacentTiles(4)).toStrictEqual({'R': 3, 'T': null, 'B': 8, 'L': null})
	expect(getAdjacentTiles(5)).toStrictEqual({'R': null, 'T': 1, 'B': 9, 'L': 6})
	expect(getAdjacentTiles(6)).toStrictEqual({'R': 5, 'T': 2, 'B': 10, 'L': 7})
	expect(getAdjacentTiles(7)).toStrictEqual({'R': 6, 'T': 3, 'B': 11, 'L': 8})
	expect(getAdjacentTiles(8)).toStrictEqual({'R': 7, 'T': 4, 'B': 12, 'L': null})
	expect(getAdjacentTiles(9)).toStrictEqual({'R': null, 'T': 5, 'B': 13, 'L': 10})
	expect(getAdjacentTiles(10)).toStrictEqual({'R': 9, 'T': 6, 'B': 14, 'L': 11})
	expect(getAdjacentTiles(11)).toStrictEqual({'R': 10, 'T': 7, 'B': 15, 'L': 12})
	expect(getAdjacentTiles(12)).toStrictEqual({'R': 11, 'T': 8, 'B': 16, 'L': null})
	expect(getAdjacentTiles(13)).toStrictEqual({'R': null, 'T': 9, 'B': null, 'L': 14})
	expect(getAdjacentTiles(14)).toStrictEqual({'R': 13, 'T': 10, 'B': null, 'L': 15})
	expect(getAdjacentTiles(15)).toStrictEqual({'R': 14, 'T': 11, 'B': null, 'L': 16})
	expect(getAdjacentTiles(16)).toStrictEqual({'R': 15, 'T': 12, 'B': null, 'L': null})
})